/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-04-13 21:27:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/web/pages/geral/header-includes.jsp", Long.valueOf(1397423432000L));
    _jspx_dependants.put("/web/pages/geral/footer.jsp", Long.valueOf(1397422475000L));
    _jspx_dependants.put("/web/pages/geral/header-banner.jsp", Long.valueOf(1397424432000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>Eu Vou Romper</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n");
      out.write("    <meta name=\"product\" content=\"\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <meta name=\"keywords\" content=\"\">\n");
      out.write("\n");
      out.write("    <link href=\"web/assets/css/metro-bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"web/assets/css/metro-bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"web/assets/css/metro-bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"web/assets/css/style-main.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"web/assets/css/revolution.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"web/assets/css/default_slider.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Load JavaScript Libraries -->\n");
      out.write("    <script src=\"web/assets/js/jquery/jquery.min.js\"></script>\n");
      out.write("    <script src=\"web/assets/js/jquery/jquery.widget.min.js\"></script>\n");
      out.write("    <script src=\"web/assets/js/jquery/jquery.mousewheel.js\"></script>\n");
      out.write("\t\n");
      out.write("    <!-- Metro UI CSS JavaScript plugins -->\n");
      out.write("\t<script src=\"web/assets/js/jquery.number.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"web/assets/js/jquery.themepunch.plugins.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    \n");
      out.write("    <!-- <script src=\"web/assets/docs/js/load-metro.js\"></script> -->\n");
      out.write("    <script src=\"web/assets/js/metro/metro.min.js\"></script>\n");
      out.write("\t<script src=\"web/assets/js/default.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"web/assets/js/plugin_revolution.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"web/assets/js/easypaginate.js\" type=\"text/javascript\" ></script>\n");
      out.write("\n");
      out.write("</head>");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"metro\" style=\"\">\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<header id=\"content-header-home\">\n");
      out.write("\n");
      out.write("\t<nav class=\"horizontal-menu-top-home compact\">\n");
      out.write("\t\t<ul class=\"\">\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<div id=\"conteiner-area-aluno\">\n");
      out.write("\t\t<h3>Área do Aluno</h3>\n");
      out.write("\n");
      out.write("\t\t<div id=\"form-area-aluno\">\n");
      out.write("\t\t\t<form action=\"\" method=\"get\" accept-charset=\"utf-8\">\n");
      out.write("\t\t\t\t<div class=\"input-control text\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" value=\"\" placeholder=\"E-mail\" />\n");
      out.write("\t\t\t\t\t<button class=\"btn-clear\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"input-control password\">\n");
      out.write("\t\t\t\t\t<input type=\"password\" value=\"\" placeholder=\"Senha\" />\n");
      out.write("\t\t\t\t\t<button class=\"btn-reveal\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"links-login\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Crie uma conta\" class=\"\">Crie uma conta</a> <a href=\"#\" title=\"Esqueceu senha?\" class=\"esqueceu-senha\">Esqueceu sua senha?</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Entrar\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"sliders hidden-phone\">\n");
      out.write("\t\t<div id=\"slider\" class=\"rev_slider fullwidthabanner\">\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li data-transition=\"papercut\" data-slotamount=\"8\" data-masterspeed=\"300\"><img src=\"http://www.iped.com.br/img/cursos/imagens-destaques/direito-administrativo.jpg\" data-fullwidthcentering=\"on\" alt=\"Curso de Direito Administrativo\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption slider-title lfb\" data-x=\"20\" data-y=\"70\" data-speed=\"800\" data-start=\"800\" data-easing=\"easeOutBack\" style=\"color: #363636 !important;\">\n");
      out.write("\t\t\t\t\t\tCurso de Direito<br />Administrativo\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption slider-paragraph lft\" data-x=\"20\" data-y=\"160\" data-speed=\"600\" data-start=\"1000\" data-easing=\"easeOutBack\" style=\"color: #363636 !important;\">\n");
      out.write("\t\t\t\t\t\tO objetivo desse curso é ensinar sobre a obrigatoriedade e<br />dispensa da licitação, sobre os sistemas administrativos,...\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption lfb\" data-x=\"20\" data-y=\"230\" data-speed=\"450\" data-start=\"1200\" data-easing=\"easeOutBack\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-large btn-largexyyy\" onclick=\"javascript:window.location='/direito/curso/direito-administrativo'\">Saiba Mais</button>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t<li data-transition=\"papercut\" data-slotamount=\"8\" data-masterspeed=\"300\"><img src=\"http://www.iped.com.br/img/cursos/imagens-destaques/direito-do-trabalho.jpg\" data-fullwidthcentering=\"on\" alt=\"Curso de Direito do Trabalho\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption slider-title lfb\" data-x=\"20\" data-y=\"100\" data-speed=\"800\" data-start=\"800\" data-easing=\"easeOutBack\" style=\"color: #363636 !important;\">Curso de Direito do Trabalho</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption slider-paragraph lft\" data-x=\"20\" data-y=\"160\" data-speed=\"600\" data-start=\"1000\" data-easing=\"easeOutBack\" style=\"color: #363636 !important;\">\n");
      out.write("\t\t\t\t\t\tO objetivo desse curso é ensinar sobre a evolução do direito<br />do trabalho, o conceito de empregador e empregado, a...\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption lfb\" data-x=\"20\" data-y=\"230\" data-speed=\"450\" data-start=\"1200\" data-easing=\"easeOutBack\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-large btn-largex\" onclick=\"javascript:window.location='/direito/curso/direito-do-trabalho'\">Saiba Mais</button>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t<li data-transition=\"papercut\" data-slotamount=\"8\" data-masterspeed=\"300\"><img src=\"http://www.iped.com.br/img/cursos/imagens-destaques/direito-constitucional.jpg\" data-fullwidthcentering=\"on\" alt=\"Curso de Direito Constitucional\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption slider-title lfb\" data-x=\"20\" data-y=\"70\" data-speed=\"800\" data-start=\"800\" data-easing=\"easeOutBack\" style=\"color: #363636 !important;\">\n");
      out.write("\t\t\t\t\t\tCurso de Direito<br />Constitucional\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption slider-paragraph lft\" data-x=\"20\" data-y=\"160\" data-speed=\"600\" data-start=\"1000\" data-easing=\"easeOutBack\" style=\"color: #363636 !important;\">\n");
      out.write("\t\t\t\t\t\tO objetivo desse curso é ensinar sobre os conceitos de<br />constituição, os princípios e objetivos fundamentais,<br />direitos...\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tp-caption lfb\" data-x=\"20\" data-y=\"230\" data-speed=\"450\" data-start=\"1200\" data-easing=\"easeOutBack\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-large btn-largex\" onclick=\"javascript:window.location='/direito/curso/direito-constitucional'\">Saiba Mais</button>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</header>");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"container\" style=\"padding: 10px\">\n");
      out.write("\t\t<div class=\"metro one-column\">\n");
      out.write("\t\t\t<h2 class=\"titles-big title-professores\">Professores</h2>\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\tjQuery(function($) {\n");
      out.write("\t\t\t\t\t$('ul#items').easyPaginate({\n");
      out.write("\t\t\t\t\t\tstep : 5,\n");
      out.write("\t\t\t\t\t\tauto : true,\n");
      out.write("\t\t\t\t\t\tloop : true,\n");
      out.write("\t\t\t\t\t\tclickstop : false,\n");
      out.write("\t\t\t\t\t\tpause : 8000\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t</script>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"container\" class=\"clear\">\n");
      out.write("\t\t\t\t<ul id=\"items\" class=\"\">\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end professores -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"metro four-column clear\">\n");
      out.write("\t\t\t\t<h2 class=\"titles-big title-cursos\">Cursos</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t<article class=\"cursos-item\">\n");
      out.write("\t\t\t\t\t<figure>\n");
      out.write("\t\t\t\t\t\t<img src=\"web/assets/imgs/figure.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t<figcaption></figcaption>\n");
      out.write("\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t<div class=\"title-curso-item\">\n");
      out.write("\t\t\t\t\t\t<h5>Concurso - Polícia Rodoviária Federal Ag. Adm</h5>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"footer-curso\">\n");
      out.write("\t\t\t\t\t\t<span>R$ 1.200,00</span> <a href=\"#\" class=\"saiba-mais-curso\" title=\"Saiba mais\">saiba mais</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t\t\t<article class=\"cursos-item\">\n");
      out.write("\t\t\t\t\t<figure>\n");
      out.write("\t\t\t\t\t\t<img src=\"web/assets/imgs/figure.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t<figcaption></figcaption>\n");
      out.write("\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t<div class=\"title-curso-item\">\n");
      out.write("\t\t\t\t\t\t<h5>Concurso - Polícia Rodoviária Federal Ag. Adm</h5>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"footer-curso\">\n");
      out.write("\t\t\t\t\t\t<span>R$ 1.200,00</span> <a href=\"#\" class=\"saiba-mais-curso\" title=\"Saiba mais\">saiba mais</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t\t\t<article class=\"cursos-item\">\n");
      out.write("\t\t\t\t\t<figure>\n");
      out.write("\t\t\t\t\t\t<img src=\"web/assets/imgs/figure.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t<figcaption></figcaption>\n");
      out.write("\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t<div class=\"title-curso-item\">\n");
      out.write("\t\t\t\t\t\t<h5>Concurso - Polícia Rodoviária Federal Ag. Adm</h5>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"footer-curso\">\n");
      out.write("\t\t\t\t\t\t<span>R$ 1.200,00</span> <a href=\"#\" class=\"saiba-mais-curso\" title=\"Saiba mais\">saiba mais</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t\t\t<article class=\"cursos-item\">\n");
      out.write("\t\t\t\t\t<figure>\n");
      out.write("\t\t\t\t\t\t<img src=\"web/assets/imgs/figure.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t<figcaption></figcaption>\n");
      out.write("\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t<div class=\"title-curso-item\">\n");
      out.write("\t\t\t\t\t\t<h5>Concurso - Polícia Rodoviária Federal Ag. Adm</h5>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"footer-curso\">\n");
      out.write("\t\t\t\t\t\t<span>R$ 1.200,00</span> <a href=\"#\" class=\"saiba-mais-curso\" title=\"Saiba mais\">saiba mais</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end cursos -->\n");
      out.write("\n");
      out.write("\t\t\t<hr class=\"line\"></hr>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"metro one-column clear\">\n");
      out.write("\t\t\t\t<h2 class=\"titles-big title-aulas-gratuitas\">Aulas gratuitas</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t<article class=\"aulas-item\">\n");
      out.write("\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"web/assets/imgs/example-videos.jpg\" width=\"220\" height=\"136\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t<div class=\"aulas-content\">\n");
      out.write("\t\t\t\t\t\t<h4>Direito Constitucional Aplicado</h4>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"assistir\" title=\"Assistir à aula\">Assistir à aula</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t\t\t<article class=\"aulas-item\">\n");
      out.write("\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"web/assets/imgs/example-videos.jpg\" width=\"220\" height=\"136\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t<div class=\"aulas-content\">\n");
      out.write("\t\t\t\t\t\t<h4>Direito Constitucional Aplicado</h4>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"assistir\" title=\"Assistir à aula\">Assistir à aula</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t\t\t<article class=\"aulas-item\">\n");
      out.write("\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"web/assets/imgs/example-videos.jpg\" width=\"220\" height=\"136\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t<div class=\"aulas-content\">\n");
      out.write("\t\t\t\t\t\t<h4>Direito Constitucional Aplicado</h4>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"assistir\" title=\"Assistir à aula\">Assistir à aula</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t\t\t<article class=\"aulas-item\">\n");
      out.write("\t\t\t\t\t<a href=\"\" title=\"\"><img src=\"web/assets/imgs/example-videos.jpg\" width=\"220\" height=\"136\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t<div class=\"aulas-content\">\n");
      out.write("\t\t\t\t\t\t<h4>Direito Constitucional Aplicado</h4>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"assistir\" title=\"Assistir à aula\">Assistir à aula</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end Aulas -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"metro one-column clear last-box\">\n");
      out.write("\n");
      out.write("\t\t\t\t<section id=\"noticias\" class=\"box3\">\n");
      out.write("\t\t\t\t\t<h2 class=\"titles-big title-noticias\">Notícias</h2>\n");
      out.write("\t\t\t\t\t<article>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"ADVOGADO LANÇA LIVRO DE 7,5 METROS\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"side-left-article\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"dia clear\">06</span> <span class=\"mes clear\">NOV</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"side-right-article\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4>ADVOGADO LANÇA LIVRO DE 7,5 METROS</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Em protesto advogado lança livro gigante. Ele dedicou 23 anos na obra.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<article>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"ADVOGADO LANÇA LIVRO DE 7,5 METROS\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"side-left-article\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"dia clear\">06</span> <span class=\"mes clear\">NOV</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"side-right-article\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4>ADVOGADO LANÇA LIVRO DE 7,5 METROS</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Em protesto advogado lança livro gigante. Ele dedicou 23 anos na obra.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</article>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\t\t\t\t<!-- end noticias -->\n");
      out.write("\n");
      out.write("\t\t\t\t<section id=\"noticias\" class=\"box3\">\n");
      out.write("\t\t\t\t\t<h2 class=\"titles-big title-depoimentos\">Depoimentos</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div id=\"depoimentos\">\n");
      out.write("\t\t\t\t\t\t<div class=\"content-depoimentos\">\n");
      out.write("\t\t\t\t\t\t\t<p>\"É um fato conhecido de todos que um leitor se distrairá com o conteúdo de texto legível de uma página quando estiver examinando sua diagramação. A vantagem de usar Lorem Ipsum é que ele tem uma distribuição normal de letras, ao contrário de “Conteúdo aqui, conteúdo aqui...”.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"autor\">Gustavo Santos Arruda, Analista de Sistemas - Ábaco Tecnologia de Informação</h5>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\t\t\t\t<!-- end noticias -->\n");
      out.write("\n");
      out.write("\t\t\t\t<section id=\"noticias\" class=\"box3\">\n");
      out.write("\t\t\t\t\t<h2 class=\"titles-big title-tv\">TV</h2>\n");
      out.write("\t\t\t\t\t<iframe width=\"347\" height=\"248\" src=\"https://www.youtube.com/embed/kGgTuEcuOoI?rel=0\" frameborder=\"0\" allowfullscreen></iframe>\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\t\t\t\t<!-- end noticias -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- end container -->\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer id=\"footer\" class=\"clear \">\n");
      out.write("\t<div id=\"footer-content\" class=\"\">\n");
      out.write("\t\t<div id=\"redes-sociais\">\n");
      out.write("\t\t\t<ul class=\"\">\n");
      out.write("\t\t\t\t<li><a href=\"\" title=\"\" class=\"facebook\">facebook</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"\" title=\"\" class=\"twitter\">twitter</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"\" title=\"\" class=\"google\">google +</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"\" title=\"\" class=\"youtube\">youtube</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end redes-sociais -->\n");
      out.write("\t\t<div id=\"informacoes\" class=\"box-footer span3 left\">\n");
      out.write("\t\t\t<span><h3>Informações</h3></span>\n");
      out.write("\n");
      out.write("\t\t\t<ul class=\"lista-footer\">\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"minha-conta\" class=\"box-footer span3 left\">\n");
      out.write("\t\t\t<span><h3>Minha Conta</h3></span>\n");
      out.write("\n");
      out.write("\t\t\t<ul class=\"lista-footer\">\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"fale-conosco\" class=\"box-footer span3 left\">\n");
      out.write("\t\t\t<span><h3>Fale conosco</h3></span>\n");
      out.write("\t\t\t<p style=\"margin-top: 15px;\">Telefone: 1-000-000-0000</p>\n");
      out.write("\t\t\t<p>Rua Teste Q. 03 Nº 04 Apto. 16</p>\n");
      out.write("\t\t\t<p>E-mail: contato@euvouromper.com.br</p>\n");
      out.write("\t\t\t<!-- <a href=\"\" title=\"\" style=\"color: #fff;\">Google Maps</a> -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"newsletter\" class=\"box-footer span3 left\">\n");
      out.write("\t\t\t<span><h3>Newsletter</h3></span>\n");
      out.write("\t\t\t<p>Receba nossas informações:</p>\n");
      out.write("\t\t\t<form action=\"\" method=\"get\" accept-charset=\"utf-8\">\n");
      out.write("\t\t\t\t<div class=\"\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" value=\"\" placeholder=\"e-mail\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Cadastrar\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"pagseguro\"></div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- end footer-content -->\n");
      out.write("</footer>");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /web/pages/geral/header-banner.jsp(10,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/web/pages/geral/header-banner.jsp(10,3) '${menusTopo}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${menusTopo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /web/pages/geral/header-banner.jsp(10,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("menu");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></li>\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /web/pages/home.jsp(28,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/web/pages/home.jsp(28,5) '${professores}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${professores}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /web/pages/home.jsp(28,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("professor");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t<li>\n");
          out.write("\t\t\t\t\t\t\t<p class=\"image\">\n");
          out.write("\t\t\t\t\t\t\t\t<a href=\"professor/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${professor.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\n");
          out.write("\t\t\t\t\t\t\t\t\t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${professor.pathFoto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${professor.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"cycle polaroid shadow\" style=\"width: 180px; height: 180px;\" />\n");
          out.write("\t\t\t\t\t\t\t\t</a>\n");
          out.write("\t\t\t\t\t\t\t</p>\n");
          out.write("\t\t\t\t\t\t\t<h3>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${professor.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</h3>\n");
          out.write("\t\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /web/pages/geral/footer.jsp(20,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/web/pages/geral/footer.jsp(20,4) '${menusRodape1}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${menusRodape1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /web/pages/geral/footer.jsp(20,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("menu");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></li>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /web/pages/geral/footer.jsp(30,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/web/pages/geral/footer.jsp(30,4) '${menusRodape2}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${menusRodape2}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /web/pages/geral/footer.jsp(30,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("menu");
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></li>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }
}
